#!/bin/sh
export PATH=$PATH:$(pwd)
set -e

which podman 2>/dev/null || alias podman=docker

all(){
  podman init
}

describe(){
  C_NORMAL="\\033[0;0m"; C_CYAN="\\033[1;36m"
  set +ex
  printf "\n$C_CYAN##################### %s ######################$C_NORMAL\n\n" "$(basename $1)"
  set -ex
}

run(){
  find .test/tests -type f | sort | xargs -n1 bash -c ; echo errors=$PIPESTATUS
}

"$@"
