#!/bin/sh

create_app(){
  header ".pod/app/simple"
  test -f app || {
    print "writing app"
    echo '#!/bin/sh\necho "PID=$(cat .pid) => $(date) PORT=$PORT"' > app
    chmod 755 app
  }
  test -f .env || {
    print "writing .env"
    PORT=$(awk 'BEGIN{ srand(); print int(rand()*1000)+8000 }')
    echo 'export PORT='$PORT   >> .env
  }
}

daemonize(){
  while sleep 1s; do 
    set +e
    ./app
    echo "$(tail -n200 app.log)" > app.log
  done
}

start(){
  test -f .pid  && { print "stopping $PODI_APP"; silent try kill -15 $(cat .pid); }
  nohup ./podi daemonize $PODI_APP:$PORT &> app.log &
  echo $! > .pid
  print "started $PODI_APP [PID $(cat .pid)]"
}

on init_localhost create_app
